/**
 * Vector PDF export with jsPDF + autotable: PA-17 (SMR) landscape A4,
 * the daily closing sheet, and a hand-over receipt.
 */
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { DailyClosing, DenominationLine, Handover, Office, SmrReport, VoucherItem } from "../types";
import { Money, type Paise } from "../money";
import { CATEGORY_LABELS, voucherTypeLabel } from "../constants";
import { formatDateLong, formatDateShort } from "../utils";

const rs = (p: Paise) => Money.format(p, { register: true });

function header(doc: jsPDF, title: string, office: Office, subtitle: string) {
  const w = doc.internal.pageSize.getWidth();
  doc.setFont("helvetica", "bold").setFontSize(13).text("DEPARTMENT OF POSTS — INDIA", w / 2, 11, { align: "center" });
  doc.setFontSize(11).text(title, w / 2, 17, { align: "center" });
  doc.setFont("helvetica", "normal").setFontSize(8.5);
  doc.text(`Office: ${office.name} (${office.pincode})   Facility ID: ${office.facility_id || "—"}   Division: ${office.division || "—"}   Sub-Division: ${office.sub_division || "—"}`, w / 2, 22.5, { align: "center" });
  doc.text(subtitle, w / 2, 27, { align: "center" });
}

function footer(doc: jsPDF, office: Office, extra = "") {
  const pages = doc.getNumberOfPages();
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal").setFontSize(7.5);
    doc.text(`NOTE: All amounts are in Indian Rupees. ${extra}`.trim(), 10, h - 12);
    doc.text(`Generated by HandToHand X on ${new Date().toLocaleString("en-IN")}   Page ${i} of ${pages}`, w - 10, h - 12, { align: "right" });
    doc.text(`Signature of ${office.postmaster_designation || "SPM"}: ______________________________   (${office.postmaster_name || " "})`, 10, h - 6);
    doc.text("Signature of verifying officer: ______________________________", w - 10, h - 6, { align: "right" });
  }
}

export function buildPa17Pdf(report: SmrReport): Uint8Array {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const o = report.office;
  header(doc, `SPM MONTHLY REPORT (PA-17) — ${report.month_label.toUpperCase()}`, o, `Opening balance of the month: ₹${rs(report.opening_balance_of_month)}   Maximum balance: ₹${rs(o.max_cash_limit)}   Minimum balance: ₹${rs(o.min_cash_limit)}   Sectioned balance of stamps: ₹${rs(report.sectioned_stamp_balance)}`);
  const head = [["Date", "Cash received", "Cash remitted", "Value of stamps received", "Value of stamps remitted", "Postage stamps", "Revenue stamps", "Other stamps", "Cash in hand", "Balance due to PO", "Closing balance", "Liabilities & explanation for excess cash"]];
  const body = report.rows.map((r) => [
    `${String(r.day).padStart(2, "0")} ${r.weekday}${r.is_holiday ? " (H)" : ""}`,
    r.is_holiday && !r.has_record ? "—" : rs(r.cash_received),
    r.is_holiday && !r.has_record ? "—" : rs(r.cash_remitted),
    rs(r.stamps_received),
    rs(r.stamps_remitted),
    rs(r.postage_stamps),
    rs(r.revenue_stamps),
    rs(r.other_stamps),
    r.has_record ? rs(r.cash_in_hand) : "—",
    r.has_record ? rs(r.balance_due_to_po) : "—",
    r.has_record ? rs(r.closing_balance) : "—",
    [r.liabilities_note, r.max_breach !== null ? `Max limit exceeded by ₹${rs(r.max_breach)}` : "", r.min_breach !== null ? `Below minimum by ₹${rs(r.min_breach)}` : ""].filter(Boolean).join("; "),
  ]);
  body.push(["TOTAL", rs(report.totals.cash_received), rs(report.totals.cash_remitted), rs(report.totals.stamps_received), rs(report.totals.stamps_remitted), "", "", "", "", "", rs(report.closing_balance_of_month), ""]);
  autoTable(doc, {
    startY: 31,
    head,
    body,
    theme: "grid",
    styles: { font: "helvetica", fontSize: 7, cellPadding: 1, lineWidth: 0.15, halign: "right", valign: "middle" },
    headStyles: { fillColor: [235, 238, 245], textColor: 20, fontStyle: "bold", halign: "center" },
    columnStyles: { 0: { halign: "left", cellWidth: 17 }, 11: { halign: "left", cellWidth: 52, fontSize: 6.5 } },
    didParseCell: (data) => {
      if (data.section === "body" && data.row.index === body.length - 1) data.cell.styles.fontStyle = "bold";
      const row = report.rows[data.row.index];
      if (data.section === "body" && row?.is_holiday) data.cell.styles.fillColor = [245, 245, 245];
      if (data.section === "body" && row && (row.max_breach !== null || row.min_breach !== null)) data.cell.styles.textColor = [170, 30, 30];
    },
    margin: { left: 8, right: 8, bottom: 18 },
  });
  const y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 5;
  if (report.stock.length) {
    autoTable(doc, {
      startY: y,
      head: [["Stamp & stationery stock", "Opening", "Receipts", "Sales", "Closing"]],
      body: report.stock.map((s) => [s.category.toUpperCase(), rs(s.opening), rs(s.receipts), rs(s.sales), rs(s.closing)]),
      theme: "grid",
      styles: { fontSize: 7, cellPadding: 1, halign: "right" },
      headStyles: { fillColor: [235, 238, 245], textColor: 20 },
      columnStyles: { 0: { halign: "left" } },
      tableWidth: 120,
      margin: { left: 8, bottom: 18 },
    });
  }
  const y2 = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 4;
  doc.setFontSize(7.5).setFont("helvetica", "normal");
  const summary = [
    `Working days: ${report.totals.working_days}   Days recorded: ${report.totals.days_recorded}   Days closed: ${report.totals.days_closed}   Highest closing: ₹${rs(report.totals.highest_closing)}   Lowest closing: ₹${rs(report.totals.lowest_closing)}`,
    `Cash limit breaches — over maximum: ${report.totals.max_breaches}, below minimum: ${report.totals.min_breaches}.   Status: ${report.status.replace(/_/g, " ").toUpperCase()}${report.signed_off_at ? `   Signed off ${new Date(report.signed_off_at).toLocaleString("en-IN")}` : ""}`,
    ...report.flags.map((f) => `• ${f}`),
  ];
  doc.text(summary, 8, y2 > 175 ? 175 : y2);
  footer(doc, o, "(H) = Holiday / Sunday. Cash in hand = Office Currency Counter total − cash items. Balance due to PO = Cash in hand.");
  return new Uint8Array(doc.output("arraybuffer"));
}

export interface ClosingSheetData {
  office: Office;
  businessDate: string;
  closing: DailyClosing | null;
  vouchers: VoucherItem[];
  handovers: Handover[];
  denominations: DenominationLine[];
  preparedBy: string;
}

export function buildClosingSheetPdf(d: ClosingSheetData): Uint8Array {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  header(doc, "DAILY HAND-TO-HAND CLOSING SHEET", d.office, `Business date: ${formatDateLong(d.businessDate)}   Prepared by: ${d.preparedBy}`);
  const c = d.closing;
  autoTable(doc, {
    startY: 31,
    head: [["Book balance", "Amount (₹)"]],
    body: [
      ["Opening balance (OB)", rs(c?.opening_balance ?? 0)],
      ["Total receipts / deposits", rs(c?.total_receipts ?? 0)],
      ["Total payments / withdrawals", rs(c?.total_payments ?? 0)],
      ["Closing balance (OB + receipts − payments)", rs(c?.closing_balance ?? 0)],
      ["System book balance (Finacle / SAP CSI)", c?.system_book_balance != null ? rs(c.system_book_balance) : "not entered"],
      ["Physical cash (Office Currency Counter)", rs(c?.physical_cash ?? 0)],
      ["Variance (physical − book)", c ? Money.signed(c.variance) : "—"],
      ["Status", c ? (c.status === "closed" ? `CLOSED ${c.closed_at ? new Date(c.closed_at).toLocaleString("en-IN") : ""}` : "OPEN") : "no record"],
    ],
    theme: "grid",
    styles: { fontSize: 8.5, cellPadding: 1.5 },
    columnStyles: { 1: { halign: "right", fontStyle: "bold" } },
    tableWidth: 120,
    margin: { left: 12 },
  });
  const byCat = new Map<string, { lines: number; count: number; receipts: Paise; payments: Paise }>();
  for (const v of d.vouchers.filter((x) => x.verification_status !== "rejected")) {
    const key = `${CATEGORY_LABELS[v.category]} › ${voucherTypeLabel(v.voucher_type)}`;
    const e = byCat.get(key) ?? { lines: 0, count: 0, receipts: 0, payments: 0 };
    e.lines++;
    e.count += v.voucher_count;
    if (v.flow === "receipt") e.receipts += v.amount; else e.payments += v.amount;
    byCat.set(key, e);
  }
  autoTable(doc, {
    startY: (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 5,
    head: [["Voucher head", "Lines", "Vouchers", "Receipts (₹)", "Payments (₹)"]],
    body: [...byCat.entries()].map(([k, e]) => [k, String(e.lines), String(e.count), rs(e.receipts), rs(e.payments)]),
    theme: "grid",
    styles: { fontSize: 8, cellPadding: 1.2 },
    columnStyles: { 1: { halign: "right" }, 2: { halign: "right" }, 3: { halign: "right" }, 4: { halign: "right" } },
    margin: { left: 12, right: 12 },
  });
  autoTable(doc, {
    startY: (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 5,
    head: [["Denomination", "Pieces", "Amount (₹)"]],
    body: d.denominations.filter((l) => l.amount > 0).map((l) => [l.kind === "mixed_coins" ? "Mixed coins" : l.kind === "citem" ? "Cash items (CITEM)" : `₹${l.face_value_paise / 100} ${l.kind}`, l.kind === "note" || l.kind === "coin" ? String(l.quantity) : "—", rs(l.amount)]),
    foot: [["Total physical cash", "", rs(d.denominations.reduce((a, l) => a + l.amount, 0))]],
    theme: "grid",
    styles: { fontSize: 8, cellPadding: 1.2 },
    columnStyles: { 1: { halign: "right" }, 2: { halign: "right" } },
    footStyles: { fontStyle: "bold", fillColor: [235, 238, 245], textColor: 20 },
    tableWidth: 100,
    margin: { left: 12 },
  });
  autoTable(doc, {
    startY: (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 5,
    head: [["Counter", "Seq", "Status", "Submitted", "Verified"]],
    body: d.handovers.map((h) => [h.counter_label, String(h.sequence_no), h.status.toUpperCase(), h.submitted_at ? new Date(h.submitted_at).toLocaleTimeString("en-IN") : "—", h.verified_at ? new Date(h.verified_at).toLocaleTimeString("en-IN") : "—"]),
    theme: "grid",
    styles: { fontSize: 8, cellPadding: 1.2 },
    margin: { left: 12, right: 12 },
  });
  footer(doc, d.office);
  return new Uint8Array(doc.output("arraybuffer"));
}

export function buildHandoverReceiptPdf(office: Office, handover: Handover, vouchers: VoucherItem[], physical: Paise): Uint8Array {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a5" });
  const w = doc.internal.pageSize.getWidth();
  doc.setFont("helvetica", "bold").setFontSize(11).text("HAND-TO-HAND RECEIPT", w / 2, 12, { align: "center" });
  doc.setFont("helvetica", "normal").setFontSize(8).text(`${office.name} (${office.pincode})   ${formatDateShort(handover.business_date)}   ${handover.counter_label} #${handover.sequence_no}`, w / 2, 17, { align: "center" });
  const receipts = vouchers.filter((v) => v.flow === "receipt").reduce((a, v) => a + v.amount, 0);
  const payments = vouchers.filter((v) => v.flow === "payment").reduce((a, v) => a + v.amount, 0);
  autoTable(doc, {
    startY: 21,
    head: [["Type", "ID", "Nos", "Amount (₹)", "Flow"]],
    body: vouchers.map((v) => [voucherTypeLabel(v.voucher_type), v.account_or_barcode_id || "—", String(v.voucher_count), rs(v.amount), v.flow === "receipt" ? "R" : "P"]),
    foot: [["Receipts", "", "", rs(receipts), ""], ["Payments", "", "", rs(payments), ""], ["Physical cash handed", "", "", rs(physical), ""]],
    theme: "grid",
    styles: { fontSize: 7.5, cellPadding: 1 },
    columnStyles: { 2: { halign: "right" }, 3: { halign: "right" } },
    footStyles: { fontStyle: "bold", fillColor: [235, 238, 245], textColor: 20 },
    margin: { left: 8, right: 8 },
  });
  const y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 12;
  doc.setFontSize(8).text("Handed over by (PA): ____________________", 8, y);
  doc.text("Received by (SPM / Treasurer): ____________________", w - 8, y, { align: "right" });
  return new Uint8Array(doc.output("arraybuffer"));
}
